blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('blog/', views.PostListView.as_view(), name="posts-list"),
    path('blog/<int:year>/<int:month>/<slug:slug>', views.PostDetailView.as_view(), name="posts-detail"),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from .settings import get_secret

ADMIN_URL = get_secret("ADMIN_URL")

urlpatterns = [
    path(ADMIN_URL, admin.site.urls),
    path('', include('main.urls')),
    path('', include('publications.urls')),
    path('', include('projects.urls')),
    path('', include('blog.urls')),
    url(r'^markdownx/', include('markdownx.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

publications/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('publications/', views.PublicationsListView.as_view(), name="publications-list"),
]

publications/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from main.models import MyInfo

class Publication(models.Model):
    """ Publication model.
    """
    BOOK = "BK"
    ARTICLE = "AR"
    CONFERENCE_PAPER = "CF"
    BOOK_CHAPTER = "BC"
    PATENT = "PT"
    TYPE_CHOICES = [
        (BOOK,'Book'),
        (ARTICLE, 'Article'),
        (CONFERENCE_PAPER,'Conference Paper'),
        (BOOK_CHAPTER, 'Book Chapter'),
        (PATENT, 'Patent')
    ]
    kind = models.CharField(
        max_length=2,
        choices=TYPE_CHOICES,
        default='AR',
        verbose_name="Publication type")

    title = models.CharField(
        max_length=200, 
        unique=True,
        verbose_name="Title")
    
    year = models.CharField(
        max_length=50, 
        verbose_name="Publishing Year",
    )

    authors = models.CharField(
        max_length=255,
        default="",
        verbose_name = "Authors",
        help_text = "Example: 'F. Author, J. Doe.'. A name can be highlighted by enclosing it in html 'strong' tags: <strong>J. Doe</strong>.", 
    )

    DEFAULT_MYINFO_ID = 1
    my_info = models.ForeignKey(
        MyInfo,
        on_delete=CASCADE,
        default=DEFAULT_MYINFO_ID)

    publisher = models.CharField(
        max_length=200, 
        default="",
        verbose_name="Publisher",
        help_text="Journal, publisher, patent provider, etc.")

    link = models.URLField(
        max_length=200,
        blank=True,
        verbose_name="External hyperlink",
        help_text="Redirects user to publication. (e.g. DOI for article)"
    )

    class Meta:
        ordering = ['kind','year', 'title']

    def authors_list(self):
        authors = self.authors.replace(
            self.my_info.my_initials,
            "<strong>"+self.my_info.my_initials+"</strong>")
        return authors

    def __str__(self):
        short_title = ' '.join(self.title.split(' ')[:5]) # Only four first words
        return f"{self.year}  - {short_title}"
    

publications/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Publication
from main.views import PageTitleMixin

# Create your views here.
class PublicationsListView(PageTitleMixin, ListView):
    model = Publication
    template_name = 'publications/publications.html'
    context_object_name = 'publications'
    ordering = ['kind','-year']
    page_title = "Publications"

publications/templates/publications/publications.html
{% extends 'main/base_listview.html' %}

{% load static %}

{% block bg_img %}
    {% static "main/ArticleDetail.svg"%}
{% endblock %}

{% block section_title %}
    Publications
{% endblock %}

{% block cards %}
    <div class="row row-cols-1 row-cols-md-2 g-md-4 d-flex justify-content-around">
        {% for pub in publications %}
                <div class="col-12 col-md-6 me-auto">
                    <div class="card pub-card h-100 text-center">
                        <strong class="py-2 font-display text-primary">{{ pub.get_kind_display }}</strong>
                        <a class="h3 pub-title card-title pb-2 font-highlight" {% if pub.link %}href={{ pub.link }} target="_blank" {% endif %}>{{ pub.title }}</a>
                        <hr class="mx-3">
                        <div class="text-start ms-3">
                        <p class="my-0 text-muted">{{ pub.publisher }}</p>
                        <p class="my-0 text-muted">{{ pub.authors_list|safe }}</p>
                        <p class="mt-0  text-muted">{{ pub.year }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
    </div>
{% endblock %}